"""Remove 'is_active' column to Content

Revision ID: 22fd14250037
Revises: 94903a7dec23
Create Date: 2025-05-02 02:56:16.705123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22fd14250037'
down_revision = '94903a7dec23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_constraint('content_campaign_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'campaign', ['campaign_id'], ['id'], referent_schema='spock_schema')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('content_campaign_id_fkey', 'campaign', ['campaign_id'], ['id'])

    # ### end Alembic commands ###
