"""Modify order(Content) to be non-nullable

Revision ID: 2831a008a737
Revises: 545a75a7a77d
Create Date: 2025-05-02 02:47:07.975207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2831a008a737'
down_revision = '545a75a7a77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('content_campaign_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'campaign', ['campaign_id'], ['id'], referent_schema='spock_schema')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('content_campaign_id_fkey', 'campaign', ['campaign_id'], ['id'])
        batch_op.alter_column('order',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
