"""empty message

Revision ID: 2afdb7d24acd
Revises: 22fd14250037
Create Date: 2025-05-03 02:18:01.517831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2afdb7d24acd'
down_revision = '22fd14250037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_constraint('content_campaign_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'campaign', ['campaign_id'], ['id'], referent_schema='spock_schema')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('content_campaign_id_fkey', 'campaign', ['campaign_id'], ['id'])

    # ### end Alembic commands ###
