"""Add 'active' column to Campaign

Revision ID: 94903a7dec23
Revises: 2831a008a737
Create Date: 2025-05-02 02:54:58.768051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94903a7dec23'
down_revision = '2831a008a737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_constraint('content_campaign_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'campaign', ['campaign_id'], ['id'], referent_schema='spock_schema')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('content_campaign_id_fkey', 'campaign', ['campaign_id'], ['id'])

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
